export const FORMATION_SLOTS = {
  "4-3-3": [
    { id: "s_gk",  label: "GK",  row: 0 },
    { id: "s_rb",  label: "RB",  row: 1 },
    { id: "s_rcb", label: "RCB", row: 1 },
    { id: "s_lcb", label: "LCB", row: 1 },
    { id: "s_lb",  label: "LB",  row: 1 },
    { id: "s_rm",  label: "RM",  row: 2 },
    { id: "s_cm",  label: "CM",  row: 2 },
    { id: "s_lm",  label: "LM",  row: 2 },
    { id: "s_rw",  label: "RW",  row: 3 },
    { id: "s_st",  label: "ST",  row: 3 },
    { id: "s_lw",  label: "LW",  row: 3 },
  ],
  "4-4-2": [
    { id: "s_gk",  label: "GK",  row: 0 },
    { id: "s_rb",  label: "RB",  row: 1 },
    { id: "s_rcb", label: "RCB", row: 1 },
    { id: "s_lcb", label: "LCB", row: 1 },
    { id: "s_lb",  label: "LB",  row: 1 },
    { id: "s_rm",  label: "RM",  row: 2 },
    { id: "s_rcm", label: "RCM", row: 2 },
    { id: "s_lcm", label: "LCM", row: 2 },
    { id: "s_lm",  label: "LM",  row: 2 },
    { id: "s_rst", label: "RST", row: 3 },
    { id: "s_lst", label: "LST", row: 3 },
  ],
  "3-5-2": [
    { id: "s_gk",  label: "GK",  row: 0 },
    { id: "s_rcb", label: "RCB", row: 1 },
    { id: "s_cb",  label: "CB",  row: 1 },
    { id: "s_lcb", label: "LCB", row: 1 },
    { id: "s_rwb", label: "RWB", row: 2 },
    { id: "s_rcm", label: "RCM", row: 2 },
    { id: "s_cm",  label: "CM",  row: 2 },
    { id: "s_lcm", label: "LCM", row: 2 },
    { id: "s_lwb", label: "LWB", row: 2 },
    { id: "s_rst", label: "RST", row: 3 },
    { id: "s_lst", label: "LST", row: 3 },
  ],
};

export function initSelection() {
  const slots = {};
  FORMATION_SLOTS["4-3-3"].forEach(sl => (slots[sl.id] = null));
  return { formation: "4-3-3", slots, bench: [] };
}

export const INITIAL_EVENTS = [
  {
    id: "evt_1",
    title: "vs Ealing Rangers",
    type: "match",
    team: "1s",
    date: "2025-03-29",
    time: "10:30",
    location: "Hurlingham Park",
    opponent: "Ealing Rangers",
    homeAway: "home",
  },
  {
    id: "evt_2",
    title: "vs Fulham Casuals",
    type: "match",
    team: "2s",
    date: "2025-03-30",
    time: "11:00",
    location: "Bishops Park",
    opponent: "Fulham Casuals",
    homeAway: "away",
  },
];

export const INITIAL_TEAMS = {
  "1s": {
    id: "1s",
    name: "Hammersmith 1s",
    match: {
      opponent: "Ealing Rangers",
      date: "Saturday 29 March",
      time: "10:30am",
      location: "Hurlingham Park",
    },
    players: [
      { id: "1s_p1",  name: "Dan Fletcher",  number: 1,  pos: "GK"  },
      { id: "1s_p2",  name: "Marcus Reid",   number: 13, pos: "GK"  },
      { id: "1s_p3",  name: "Tom Ashby",     number: 2,  pos: "DEF" },
      { id: "1s_p4",  name: "Jake Connell",  number: 5,  pos: "DEF" },
      { id: "1s_p5",  name: "Ryan Booth",    number: 6,  pos: "DEF" },
      { id: "1s_p6",  name: "Sam Porter",    number: 3,  pos: "DEF" },
      { id: "1s_p7",  name: "Chris Daly",    number: 4,  pos: "DEF" },
      { id: "1s_p8",  name: "Aaron West",    number: 8,  pos: "MID" },
      { id: "1s_p9",  name: "Josh Henley",   number: 16, pos: "MID" },
      { id: "1s_p10", name: "Callum Price",  number: 10, pos: "MID" },
      { id: "1s_p11", name: "Matty Burns",   number: 14, pos: "MID" },
      { id: "1s_p12", name: "Danny Cole",    number: 7,  pos: "MID" },
      { id: "1s_p13", name: "Ellis Shaw",    number: 9,  pos: "FWD" },
      { id: "1s_p14", name: "Tyler Moore",   number: 11, pos: "FWD" },
      { id: "1s_p15", name: "Ollie Grant",   number: 18, pos: "FWD" },
      { id: "1s_p16", name: "Marcus Webb",   number: 21, pos: "FWD" },
    ],
  },
  "2s": {
    id: "2s",
    name: "Hammersmith 2s",
    match: {
      opponent: "Fulham Casuals",
      date: "Sunday 30 March",
      time: "11:00am",
      location: "Bishops Park",
    },
    players: [
      { id: "2s_p1",  name: "Will Garner",   number: 1,  pos: "GK"  },
      { id: "2s_p2",  name: "Pete Nolan",    number: 13, pos: "GK"  },
      { id: "2s_p3",  name: "Ben Archer",    number: 2,  pos: "DEF" },
      { id: "2s_p4",  name: "Finn Walsh",    number: 5,  pos: "DEF" },
      { id: "2s_p5",  name: "Liam Cross",    number: 6,  pos: "DEF" },
      { id: "2s_p6",  name: "Harry Stone",   number: 3,  pos: "DEF" },
      { id: "2s_p7",  name: "Nathan Kirk",   number: 4,  pos: "DEF" },
      { id: "2s_p8",  name: "George Finn",   number: 8,  pos: "MID" },
      { id: "2s_p9",  name: "Leo Banks",     number: 16, pos: "MID" },
      { id: "2s_p10", name: "Tom Rowe",      number: 10, pos: "MID" },
      { id: "2s_p11", name: "Kyle Sharp",    number: 14, pos: "MID" },
      { id: "2s_p12", name: "Aiden Fox",     number: 7,  pos: "MID" },
      { id: "2s_p13", name: "Joe Mead",      number: 9,  pos: "FWD" },
      { id: "2s_p14", name: "Rhys Owen",     number: 11, pos: "FWD" },
      { id: "2s_p15", name: "Connor Dale",   number: 18, pos: "FWD" },
      { id: "2s_p16", name: "Jamie Hunt",    number: 21, pos: "FWD" },
    ],
  },
};
